lsf: 
    user: "user"
    password: "test123"
#Setzte diese Variable auf true um einen Notenspiegel zu hosten
webpage: false
mailgun:
    domain: ""
    api-key: ""
    sender-name: "Notenservice"
    reciver: ""
    subject: "Notenupdate!"